print("hello world")
print("jayasimhasai")
age = 20
print (age + 1)
name = input("enter your name: ")
print(name)
a = int(input("enter a value which touwant to add:"))
b = int(input("enter b value:"))
print(a + b)
a = int(input("enter a value which you want to multiply:"))
b = int(input("enter b value:"))
print(a * b)
n = int(input())
print(n * n)
print(n * n * n)
print(type(10))
print(type(7.77))
print(type("sai"))
print(type(True))
print(type(False))
a = 5
b = 10
a, b = b, a
print(a)
print(b)
age = int(input("enter your age:"))
print(age+10)
print("sahho")
city = input("enter your city")
print(city)
a = int(input("enter a number that you want to differene:"))
b = int(input("enter b:"))
print (a - b)
a = int(input("enter a number that you want to divide:"))
b = int(input("enter b:"))
print (a / b) 
name = input("Enter your name: ")
Birth_year = int(input("Enter your Birth year: "))

print(f"Hello {name}")
print(f"You are approximately {2025 - Birth_year} old in 2025.")
print(f"Welcome to python programming!") 
